import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ThemeProvider } from '@/providers/theme-provider';
import { SheetProvider } from '@/providers/sheet-provider';
import { Header } from '@/components/header/header';
import { Footer } from '@/components/footer';
import './globals.css';

// Define local font
const satoshi = localFont({
	src: [
		{
			path: './fonts//Satoshi-Light.woff',
			weight: '300',
			style: 'normal',
		},
		{
			path: './fonts//Satoshi-Regular.woff',
			weight: '400',
			style: 'normal',
		},
		{
			path: './fonts//Satoshi-Medium.woff',
			weight: '500',
			style: 'normal',
		},
		{
			path: './fonts/Satoshi-Bold.woff',
			weight: '700',
			style: 'normal',
		},
	],
	variable: '--font-satoshi', // CSS variable for use in Tailwind
});

const integral = localFont({
	src: './fonts/IntegralCF-DemiBold.woff',
	variable: '--font-integral', // CSS variable for use in Tailwind
	weight: '700',
});

export const metadata: Metadata = {
	title: 'Shop',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${satoshi.variable} ${integral.variable} antialiased`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					<>
						<SheetProvider />
						<Header />
						<main className="flex-1 pt-10 lg:pt-20">{children}</main>
						<Footer />
					</>
				</ThemeProvider>
			</body>
		</html>
	);
}
